name: nosql_dart
description: "Package to connect to NoSQL Hive database in Dart."
version: 0.0.5+1
home_page: http://www.icodeforyou.com
publish_to: none # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.3.0 <4.0.0" # % flutter --version => values of "Dart"
  flutter: ">=3.19.0"

dependencies:
  equatable: ^2.0.5 # Simplify Equality Comparisons
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6 # A Flutter package that helps implement the BLoC (Business Logic Component) design pattern.
  hive_flutter: ^1.1.0 # A lightweight and blazing fast key-value database written in pure Dart.
  logger: ^2.3.0 # A powerful logging package for Dart.
  path_provider: ^2.1.3 # A Flutter plugin for finding commonly used locations on the filesystem.
  ui_shared:
    git: https://github.com/GitHubStuff/ui_shared_flutter.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  build_runner: ^2.4.11 # provides a concrete way of generating files using Dart code
  flutter_lints: ^4.0.0
  matcher: ^0.12.16+1 # A library for writing matcher functions, the building block for doing test-driven development (TDD) in Dart.
  mockito: ^5.4.4 # Mock library for Dart inspired by Mockito.
  file: ^7.0.0 # A pluggable, mockable file system abstraction for Dart.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
